# Generated by Django 6.0.6 on 2026-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('current_workload', models.IntegerField(default=0)),
                ('performance_score', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
