# Generated by Django 6.0.6 on 2026-06-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_employee',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='required_position',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
