# Generated by Django 6.0.6 on 2026-07-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_ai_score_employee_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='performance_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(),
        ),
    ]
